### PR TITLE
Extract Base functionality from S3 Loading Strategy

### PR DESCRIPTION
**Pull request by darnould**
gif

## Problem

We need to support accessing archived content from S3 that no longer needs sequencing by DynamoDB.

## Solution

Prepatory refactor: extract `S3::Base`, create `S3::Sequenced < S3::Base` with sequencing functionality, for a subsequent `S3::Archived < S3::Base` to be added.

## Release

**Major**.  Consuming application now needs to point to either `Sequenced` or `Archived` - previously used  an `S3` class (now a module).

### CODE REVIEW

**Comment by stevenjack** [comment]
really nice :+1:

**Comment by stevenjack** [comment]
Can we get the travis build passing otherwise the label on the PR is going to state `build failing`

**Comment by revett** [comment]
:cake: after Rubocop offences have been fixed.

**Comment by darnould** [comment]
Looks like we've got a few Rubocop configurations to iron out first :)

**Pull request closed without merging**
